### ISSUE TITLE
Kenya Education Site

### ISSUE THREAD

**Issue by gundersen** [developmentseed/kenya-bank#1]
@mayarichman @smit1678 We are going to do a light site visualizing [Kenya education data](https://opendata.go.ke/browse?category=Education) from the [kenya open data portal](https://opendata.go.ke/). 
## Process and schedule

We are being brought in for both strategy and building and design. So this is largely in our control. The high level goal is 'make something awesome with education data form Kenya'. Scope wise we have a good week on this for two people - I think that will be plenty and we can bring in someone (like Jue) for design. 

We are still finalizing this contract, so I don't want to run too fast here but I want to be able to have a full data review so we know what we can build and a light wireframe for the site done by mid week. 
## Data prep

As you can see from the site there are 27 sets of education data sets on the Kenya data portal that I liked to above. I would like to spend 1 day with the two of you looking over the data and writing up potential cool mashups. Ideally this sites lets us map all the schools in the country and provides a lawyer switcher to provide other contexturalized data that help tell a story. Maybe a layout like http://data.awidercircle.org or data.nai.org.af meets nigeria.mixmarket.org 
## Next actions

Can you two review the data in the Kenya open data site, come up with a list of layers that could be cool, and wire out (pen and paper is fine) a site and how it could look? I want to have a plan done by COB tomorrow.

**Comment by smit1678** [comment]
@gundersen  

There is good data to work with here. We began looking at the major education indicators that are being used to track development goals. We've drafted up two wiki pages that are a start for the data outline and the wireframes: [data layers](https://github.com/developmentseed/kenya-bank/wiki/Dataset-and-Layer-Choices), [wireframes](https://github.com/developmentseed/kenya-bank/wiki/site-wireframes). We have 24 layers at the moment. 

I'd like to take a look at nailing two things with the site:  
1. density maps of school locations, giving an alternative between point locations 
2. super easy and fast layer switching between male and female indicators. Since most indicators are broken down by gender, working on a good method to switch between layers will be key to browsing the data. This can also be done with the point and density maps.  

## Next actions
- @mayarichman will take a look at the wireframes and offer any suggestions or take it a different direction. 
- @gundersen - are there additional scope/narrative details other than 'something awesome with education data'? My thinking here is that if there is an aspect that they are interested in communicating that will help with narrating with data as well as design.

**Comment by gundersen** [comment]
@smit1678 2 requests:
- get me a budget 
- what kind of site is this? A site like Nai? Or a site like Sahel or a site like One? Basically Nai is a tight story. Sahel is a lawyer switcher crazy ness, One is a story arch of a couple of different things. In my mind these all have very different scopes and goals. Based on the data listing I am seeing it sounds like you want to try to run with as much data as possible, rather than trying to do a "StumbleSafley" play, where you tell an amazing story. Thoughts?

**Comment by gundersen** [comment]
I think we should take a tight editorial angle here. What story lines are there that we could build the site around?

**Comment by smit1678** [comment]
@gundersen ok, we see three options to pitch. Two are lighter lifts, and one a medium lift. Two and three are similar but three is a more robust site around gender equity.  

Resource wise for design, data, and build: 
- option 1 = ~23 eggrolls
- option 2 = ~24 eggrolls
- option 3 = ~30 eggrolls

Draft note: 

After looking through the available data on the Kenya Open Data portal, we think there is a strong site to be assembled around 8 datasets. The overall site will look at placing Kenya's primary and secondary school locations within the context of constituency and district wide literacy and net attendance rates, broken down by gender.  

We see two options to focus on for the site:  

### Option 1: Visualizing Locations of Primary and Secondary Schools in Kenya

A light layer switcher site showcasing school location data by switching between primary and secondary school locations. This will focus users to browse through primary and secondary location data and allow users to toggle contextual education and demographic data. Interactivity will be enabled for each school location to see name, type, total enrollment. This site will have at least 6 layers. 

Data list: 
- School locations, by primary and secondary 
- Literacy rates, total
- Net attendance ratio, average
- Percent Never Attending School and Reason
- Poverty Rate
- Population 

Similar to: http://nigeria.mixmarket.org/  

Cost: $12,000     

### Option 2: Comparing Gender Equality in Primary Schools in Kenya

A light layer switcher site focusing on allowing comparisons between boys and girls primary education indicators. The site will focus layer switching to toggle between indicators by gender in the context of other education and demographic data layers. This site will have at least 10 layers. 

Data layer list:
- Primary School locations
- Literacy, by gender ratio
- Net attendance ratio, boys/girls 
- Percent Never Attending School and Reason 
- Poverty Rate  
- Population, male and female 

Similar to: http://nigeria.mixmarket.org/  

Cost: $15,000

### Option 3: Comparing Gender Equality in Primary and Secondary Schools in Kenya

A larger layer switcher site focusing on allowing comparisons between boys and girls education indicators. The site will focus layer switching to toggle between indicators by gender in the context of other education and demographic data layers. In addition, we will add several other contextual datasets to increase the browsing capabilities. This site will have at least 15 layers. 

Data layer list:
- School locations, by primary and secondary  
- School location density 
- Literacy, total and by gender ratio
- Net attendance ratio, boys/girls 
- Average Pupil-teacher ratio, primary/secondary
- Percent Never Attending School and Reason 
- Poverty Rate  
- Population, male and female 

Similar to: http://data.nai.org.af/ but with a more robust layer switcher to capture all the layers

Cost: $25,000

**Comment by gundersen** [comment]
I sent this writeup to Edward Anderson. Closing.
