### ISSUE TITLE
wrapping up Keyna

### ISSUE THREAD

**Issue by gundersen** [developmentseed/kenya-bank#11]
@mayarichman @davejohn nice work, Edward is sold on the maps that we have done so far :). The last data set we need to map is the performance data for schools. 

I know you guys are both meeting with @smit1678 @tristen tomorrow at 10am. Nate met w/ Edward in Moldova - helped prep him, and needs to be the one that makes the final sale on the site. I have asked him to review the site you guys have done and see if he has any suggestions to help packaged everything event tighter, now that we have. 

@tristen is going to rock a design touch on the site and do a code review for @mayarichman (you two can meet and debrief on Tuesday. 

The only part that is not one, that needs to be, is the /data section by @MateoV - but I don't know what his schedule is looking like. 

Ideally we get the site done done by DOB on Tuesday and then demo it to them next Thursday and just deliver it. Clearly everyone does not need to be in on this. 

How does this all sound?

**Comment by smit1678** [comment]
This conversation is old. Closing this out.
