### ISSUE TITLE
results change map interactivity

### ISSUE THREAD

**Issue by smit1678** [developmentseed/kenya-bank#15]
@mayarichman 

I think the exam results change map could have the interactivity reorganized a little bit to emphasize the value of change. What do you think of rearranging like this? But put 2006 on the left and 2010 on the right. 

![](https://img.skitch.com/20120604-ba1p42d18qbx6e9jpe1gykd6am.png)

**Comment by mayarichman** [comment]
@smit1678  Hey nate, can't see the picture, but i'd agree with a change.

**Comment by mayarichman** [comment]
Changes pushed to repo, closing.
