### ISSUE TITLE
icons for data and methodology section

### ISSUE THREAD

**Issue by smit1678** [developmentseed/kenya-bank#16]
@tristen 
cc/ @mayarichman 

What are your thoughts here? I don't want to disrupt the design aesthetic too much, but what do you think of two icons here? We need links to the /open section and the Methodology modal. Or do we stick with "Data" and then use "?" for the methodology modal?

![](https://img.skitch.com/20120605-qq7a761ynw6thph7w2se7xwk22.png)

**Comment by tristen** [comment]
I like this approach whether we go with text or icons. I'll keep this on my radar to implement - need to set out some time for this.

**Comment by smit1678** [comment]
We did not implement any icons for this. Just used "Data" and "?" for the sections. Closing this out.
