### ISSUE TITLE
world bank education account

### ISSUE THREAD

**Issue by smit1678** [developmentseed/kenya-bank#17]
@mayarichman I've created an account for this project: https://tiles.mapbox.com/worldbank-education. We need to start populating it with tiles.  

Can you start uploading the final versions of all the layers?  

Password is wbeducation2012

**Comment by smit1678** [comment]
Tiles have been uploaded. @mayarichman we need to make sure they are labeled nicely. Can you look at editing the name in the metdata on Monday?

**Comment by mayarichman** [comment]
@smit1678 

The labels are all fixed. Except I couldn't find the newly uploaded MBTiles for the schools with the lower case categories. Are they on your account?

**Comment by smit1678** [comment]
@mayarichman I uploaded them and added the lower case labels. It looks like the capitalization is not happening on the site though.

**Comment by mayarichman** [comment]
Capitalized and metadata taken care of. Closing.
