### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by mayarichman** [developmentseed/kenya-bank#2]
## Data Processing

The following layers require some mathematical transformations, including the creation of gender ratios or aggregate value, before we can join them to district and constituency administrative level shape files. 

The datasets will be chosen first from the ghost note Nate has written, starting with the most common layers for all three options.

| Layer | Action |
| :-- | :-- |
| School locations, by primary and secondary | Clean up dataset to include only relevant columns |
| Literacy rates, total | Average male and female percentages for "Can Read/Write" |
| Population | Aggregate sublocations and locations for population by district |

When these are complete, I will move on to calculating more gender specific differences for:
- Literacy
- Net Attendance
- Reason for Not Attending School
- Population

Steps to process:  
- Create 5 polygon spatial files (sqlite) in mercator projection: province, district, and division, location and sublocation
- Create data sqlite files with province, district, divisons, locations and sublocations ID's, depending on what the data provides, and run calculations from original data tables.  
- Create /data folder in `kenya-bank` repo and push spatial and data files to repo

**Comment by mayarichman** [comment]
@smit1678 

## Data Processing: Update

| Layer | Name of New Table | Added columns | Already Present |
| :-- | :-- | :-- | :-- |
| Literacy | literacy_mfa_gender | gender-ratio (Male/Female), Male/Female Average % Read/Write | Male % Read/Write, Female % Read/Write, Total Count |
| Net Attendance | net_attendance_mfa_gender | gender-ratio (Male/Female) | Male, Female, Average, Total, School |
| Population | population_mft_district_density, population_mft_province_density | Male, Female, Average, Area, Total Population, Density | Changed aggregate level (by district and province) |

All other tables were not changed due to lack of necessary detail or were already formatted well. The Population_Density dataset in the added kenya_datasets.sql, found in the <strong>/data</strong> folder, is the only dataset that reaches admin 5, but the new tables:  population_mft_district_density and population_mft_province_density, allow for spatial joins to the district and province level. Just depends on how we want to show the layers. 

The kenya_datasets.sql file holds all the original tables and newly synthesized tables. The other sqlite files are the admin layers from 1-5.

**Comment by smit1678** [comment]
Processed data and tilemill projects are now housed in the repo. Closing.
