### ISSUE TITLE
recap note for Edward

### ISSUE THREAD

**Issue by gundersen** [developmentseed/kenya-bank#9]
@smit1678 

Can you draft a recap note for Edward selling him on the scope that he signed off on today. 

Recapping yes

> Edward, 
> I just wanted to recap on the scope you signed off on yesterday to 100% make sure we have this tight. xxxxxxx sections xxxx with the goal of xxxxx. 
> - xxx
> - xxx
> - xxx

In short this site will sow the art of the possible with xxxxxx. 

> Nate

**Comment by smit1678** [comment]
We've replied here and have received sign off from regarding scope for completing the site.
